---
output: html_document
---

# Resume

<br>

### $\underline{Work\space Experience}$
Graduate Asssistant - The University of Toledo, August 2019 - May 2020.

<br>

Teaching Assistant / Research Assistant - Luleå University of Technology, January 2019 - June 2019.

<br>

Research Assistant - The RATIO Institute, November 2018 - January 2019.

<br>

### $\underline{Education}$

PhD in Economics - Luleå University of Technology, August 2020 - Current.

<br>

Master of Arts in Business and Economics (Major in Economics) - The University of Toledo, August 2019 - May 2020.

<br>

1- year Master of Science in Business and Economics (Major in Economics) - Luleå University of Technology, August 2018 - June 2019.

<br>

Bachelor of Art in Business and Economics (Major in Economics) - Luleå University of Technology, August 2016 - June 2018.

<br>

Economics and Ethics (Separate courses) - Luleå University of Technology, January 2014 - May 2014.

<br>

Higher Education Diploma in Real Estate Brokerage - Luleå University of Technology, August 2011 - June 2013.

<br>

### $\underline{Teaching\space Experience}$

Lecturer in Economics for Real Estate Agents - Luleå University of Technology / Lexicon.

<br>

Seminar Teacher in Microeconomics & Macroeconomics - Luleå University of Technology.

<br>

### $\underline{Other\space Academic\space Experience}$

PhD Student Representative in the ETKS management team at Luleå University of Technology.

<br>

Vice Chairperson & Secretary for the PhD Student Association at Luleå University of Technology.

<br>

Jury Member for the Supervisor of the Year award 2021 at Luleå University of Technology.
